version: "3"

services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: mysql_global
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: home
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - mysqlData:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma_mysql
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8182:80

volumes:
  mysqlData:
    driver: local
